apiVersion: apps/v1
kind: Deployment
metadata:
  name: crack-segmentation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crack-segmentation
  template:
    metadata:
      labels:
        app: crack-segmentation
    spec:
      containers:
      - name: crack-segmentation
        image: <your-username>/crack-segmentation:latest
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "2Gi"
            cpu: "500m"
          limits:
            memory: "4Gi"
            cpu: "2"
---
apiVersion: v1
kind: Service
metadata:
  name: crack-segmentation
spec:
  selector:
    app: crack-segmentation
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: NodePort